const users = [
  {
    email: 'caitlin.adams@example.com',
    firstName: 'caitlin',
    lastName: 'adams',
    headline: 'Legacy Configuration Orchestrator',
    username: 'brownmouse513',
    avatar: 'https://randomuser.me/api/portraits/thumb/women/90.jpg',
    auth0id: '20d0aa20-4840-4127-8063-a781e698bde3',
  },
  {
    email: 'jenny.williamson@example.com',
    firstName: 'jenny',
    lastName: 'williamson',
    headline: 'Future Tactics Consultant',
    username: 'organicbear668',
    avatar: 'https://randomuser.me/api/portraits/thumb/women/48.jpg',
    auth0id: '7f9ba766-5c77-4aee-a739-0a977402c08b',
  },
  {
    email: 'rhonda.horton@example.com',
    firstName: 'rhonda',
    lastName: 'horton',
    headline: 'Human Resonance Producer',
    username: 'lazyzebra545',
    avatar: 'https://randomuser.me/api/portraits/thumb/women/36.jpg',
    auth0id: 'c659b6c9-6e07-4965-aa78-f7af6f87f36c',
  },
  {
    email: 'ouardia.duivenvoorden@example.com',
    firstName: 'ouardia',
    lastName: 'duivenvoorden',
    headline: 'Senior Implementation Supervisor',
    username: 'silvercat216',
    avatar: 'https://randomuser.me/api/portraits/thumb/women/35.jpg',
    auth0id: 'b3714918-e4a3-41a8-a8ec-22d35c32586d',
  },
  {
    email: 'priscilla.robertson@example.com',
    firstName: 'priscilla',
    lastName: 'robertson',
    headline: 'Senior Configuration Designer',
    username: 'whitemouse889',
    avatar: 'https://randomuser.me/api/portraits/thumb/women/19.jpg',
    auth0id: 'ccbb2212-9aac-43ca-b77e-ae233fe65d60',
  },
  {
    email: 'anthony.white@example.com',
    firstName: 'anthony',
    lastName: 'white',
    headline: 'Legacy Optimization Orchestrator',
    username: 'greenwolf741',
    avatar: 'https://randomuser.me/api/portraits/thumb/men/63.jpg',
    auth0id: '1fd2feca-99ad-4941-855e-b5ba5356c546',
  },
  {
    email: 'isaac.roberts@example.com',
    firstName: 'isaac',
    lastName: 'roberts',
    headline: 'Global Identity Consultant',
    username: 'bigsnake450',
    avatar: 'https://randomuser.me/api/portraits/thumb/men/39.jpg',
    auth0id: '7912365f-c20b-43a2-9c1d-6086bc09426c',
  },
  {
    email: 'adam.lavigne@example.com',
    firstName: 'adam',
    lastName: 'lavigne',
    headline: 'Senior Ideation Representative',
    username: 'ticklishbird779',
    avatar: 'https://randomuser.me/api/portraits/thumb/men/70.jpg',
    auth0id: '08cbea00-d4da-4d74-82d0-c59b8878102f',
  },
  {
    email: 'luis.black@example.com',
    firstName: 'luis',
    lastName: 'black',
    headline: 'Relational Program Developer',
    username: 'brownduck767',
    avatar: 'https://randomuser.me/api/portraits/thumb/men/66.jpg',
    auth0id: 'a1f6ccd6-2453-416d-8633-b82ad089c063',
  },
  {
    email: 'juan.ross@example.com',
    firstName: 'juan',
    lastName: 'ross',
    headline: 'Dynamic Paradigm Officer',
    username: 'purplesnake426',
    avatar: 'https://randomuser.me/api/portraits/thumb/men/83.jpg',
    auth0id: '8cd6c172-817a-418a-8d9d-5dcdc1f8e697',
  },
]

const usernames = [
  'brownmouse513',
  'organicbear668',
  'lazyzebra545',
  'silvercat216',
  'whitemouse889',
  'greenwolf741',
  'bigsnake450',
  'ticklishbird779',
  'brownduck767',
  'purplesnake426',
]

module.exports = {
  users,
  usernames,
}
